DATA_DIR = "data/"

DATE = "2019-03-04"

DATABASE_URI = "sqlite:////tmp/github-flask.db"

CESIUM_KEY = "CHANGE"

SECRET_KEY = "CHANGE"

GITHUB_CLIENT_ID = "CHANGE"

GITHUB_CLIENT_SECRET = "CHANGE"

GITHUB_REPO_OWNER = "CHANGE"

GITHUB_REPO_NAME = "CHANGE"

GITHUB_ACCESS_TOKEN = "CHANGE"

FULLSTORY_ORG_CODE = "CHANGE"

FULLSTORY_API_KEY = "CHANGE"
